version: 2

updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "io.netty:*"
      - dependency-name: "com.fasterxml.jackson.core:*"
      - dependency-name: "com.fasterxml.jackson.module:*"
   ignore:
    - dependency-name: "io.netty:*"
      update-types:
        major
        minor
  - package-ecosystem: "maven"
    directory: "/core-io-deps"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "io.netty:*"
      - dependency-name: "com.fasterxml.jackson.core:*"
      - dependency-name: "com.fasterxml.jackson.module:*"
   ignore:
    - dependency-name: "io.netty:*"
      update-types:
        major
        minor
